version: '3.13'

services:
  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1